### ISSUE TITLE
Parameter rain-weekly incorrectly mapped to WD parameter 7

### ISSUE THREAD

**Issue by CompKingCanada** [bpaauwe/wdpoly#2]
A workaround normally would be to to remove this in config.

This wouldn't be a issue, but logic exists which recreates the poor mapping when it is removed.

WD paramater 7 should defaulted to rain-daily

WD doesn't have a "Weekly" rain metric

**Comment by bpaauwe** [comment]
Thanks for the pull request. I've merged it so I think this can be closed now.
