### ISSUE TITLE
Windspeed Unit of Measure in clientraw.txt format

### ISSUE THREAD

**Issue by CompKingCanada** [bpaauwe/wdpoly#4]
Using "metric" for unit of measure, shows units in km/h in ISY (as desired)

As per technical specs of clientraw.txt, wind speed is output from WD in Knots (kts)

The values are showing up without conversion in ISY

Great resource at [https://saratoga-weather.org/wdparser/] for looking at format of clientraw.txt

To convert from kts to km/h, the values from WD need to be multiplied by 1.852 to get to km/hr

**Comment by CompKingCanada** [comment]
P.S.  Just starting out on this path to replace my previous climate module in ISY.  I am new to Polyglot and I am also a beginner in github.

I see there is also a generic NodeServer for multiple local devices "WeatherPoly - 0.1.11" which may have more current updates/more active users.

Would you rather spend time working on the generic version, or would time best be spent working on the WD one since it would have isolated issues from other devices.  [I tried setting this up on WD to see if I could get it to work, and failed the first time]

**Comment by CompKingCanada** [comment]
#5

**Comment by CompKingCanada** [comment]
> I see there is also a generic NodeServer for multiple local devices "WeatherPoly - 0.1.11" which may have more current updates/more active users.

> Would you rather spend time working on the generic version, or would time best be spent working on the WD one since it would have isolated issues from other devices. [I tried setting this up on WD to see if I could get it to work, and failed the first time]

Opinion?

**Comment by bpaauwe** [comment]
This should be fixed now.  Thanks for the pull requests.

P.S. I try to support all of the node servers I've published so I don't have a preference between this an WeatherPoly.  At some point I may deprecate this but I'd make sure all the functionality was migrated to WeatherPoly first.
