### ISSUE TITLE
Temperature category of nodes don't appear in available option while making UDI Programs

### ISSUE THREAD

**Issue by CompKingCanada** [bpaauwe/wdpoly#7]
Under "Status", options available for creating conditions in programs, only the following major categories are available. 

- Barometric Pressure
- Humidity
- Illumination
- Wind

 Temperature is missing as an option in UDI

**Comment by CompKingCanada** [comment]
Also missing Precipitation from program options in UDI

**Comment by CompKingCanada** [comment]
#8 Should fix it...

**Comment by bpaauwe** [comment]
Thanks for the pull requests.

I've merged them and did do some commit message updates and squashed a couple together so you'll need to do a pull -f or fetch  and reset --hard to update your local repository to match the current version.

**Comment by CompKingCanada** [comment]
pull -f still didn't work.  Had error fatal: refusing to merge unrelated histories.  Didn't like my changes made locally on the PolyGlot server

Guess I have lots to learn still!  :)  Ended up having remove/reinstall.

Thanks for doing those updates!  They work like a charm..

**Comment by CompKingCanada** [comment]
Maybe one day I'll learn how do to the Pull Request (or is it a push) right from the unix git command and push those directly to your remote repository on GitHub?  Or is that not a good idea?

For example: Make proposed changes on my PolyGlot directly so I can test the changes before requesting them...
